<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Drifter_s_Atlas</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <InvariantGlobalization>true</InvariantGlobalization>
	 <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <Deterministic>false</Deterministic>
	  <AssemblyVersion>0.2.*</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Raylib-cs" Version="7.0.1" />
  </ItemGroup>
    
   <ItemGroup>
     <Content Include="Resources\**\*"
              Exclude="Resources\bg_TitleBlank.png">
       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
     </Content>
    </ItemGroup>

</Project>
